# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: global_session 3.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "global_session"
  s.version = "3.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Tony Spataro"]
  s.date = "2014-12-31"
  s.description = "This Rack middleware allows several web apps in an authentication domain to share session state, facilitating single sign-on in a distributed web app. It only provides session sharing and does not concern itself with authentication or replication of the user database."
  s.email = "support@rightscale.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".travis.yml",
    "CHANGELOG.rdoc",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "global_session.gemspec",
    "init.rb",
    "lib/global_session.rb",
    "lib/global_session/configuration.rb",
    "lib/global_session/directory.rb",
    "lib/global_session/encoding.rb",
    "lib/global_session/keystore.rb",
    "lib/global_session/rack.rb",
    "lib/global_session/rails.rb",
    "lib/global_session/rails/action_controller_class_methods.rb",
    "lib/global_session/rails/action_controller_instance_methods.rb",
    "lib/global_session/session.rb",
    "lib/global_session/session/abstract.rb",
    "lib/global_session/session/v1.rb",
    "lib/global_session/session/v2.rb",
    "lib/global_session/session/v3.rb",
    "rails/init.rb",
    "rails_generators/global_session/USAGE",
    "rails_generators/global_session/global_session_generator.rb",
    "rails_generators/global_session/templates/global_session.yml.erb",
    "rails_generators/global_session_authority/USAGE",
    "rails_generators/global_session_authority/global_session_authority_generator.rb"
  ]
  s.homepage = "https://github.com/rightscale/global_session"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Secure single-domain session sharing plugin for Rack and Rails."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, ["~> 1.4"])
      s.add_runtime_dependency(%q<rack-contrib>, ["~> 1.0"])
      s.add_runtime_dependency(%q<right_support>, ["< 4.0", ">= 2.8.2"])
      s.add_runtime_dependency(%q<simple_uuid>, [">= 0.2.0"])
      s.add_development_dependency(%q<ruby-debug>, ["~> 0.10"])
      s.add_development_dependency(%q<pry>, ["~> 0.10"])
      s.add_development_dependency(%q<pry-byebug>, ["~> 2.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
    else
      s.add_dependency(%q<json>, ["~> 1.4"])
      s.add_dependency(%q<rack-contrib>, ["~> 1.0"])
      s.add_dependency(%q<right_support>, ["< 4.0", ">= 2.8.2"])
      s.add_dependency(%q<simple_uuid>, [">= 0.2.0"])
      s.add_dependency(%q<ruby-debug>, ["~> 0.10"])
      s.add_dependency(%q<pry>, ["~> 0.10"])
      s.add_dependency(%q<pry-byebug>, ["~> 2.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    end
  else
    s.add_dependency(%q<json>, ["~> 1.4"])
    s.add_dependency(%q<rack-contrib>, ["~> 1.0"])
    s.add_dependency(%q<right_support>, ["< 4.0", ">= 2.8.2"])
    s.add_dependency(%q<simple_uuid>, [">= 0.2.0"])
    s.add_dependency(%q<ruby-debug>, ["~> 0.10"])
    s.add_dependency(%q<pry>, ["~> 0.10"])
    s.add_dependency(%q<pry-byebug>, ["~> 2.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
  end
end

